base: 'https://www.luegjobs.ch/'
baseVariants:
  -
    base: 'https://lueg.ddev.site/'
    condition: 'applicationContext == "Development"'
dependencies:
  - in2code/powermail-main
  - in2code/powermail-dropin-main
  - in2code/powermail-dropin-marketing
  - in2code/powermail-dropin-styling
  - lueg/site-package
languages:
  -
    title: Deutsch
    enabled: true
    languageId: 0
    base: /
    locale: de_CH.UTF-8
    navigationTitle: Deutsch
    flag: ch
    hreflang: de-CH
    websiteTitle: ''
rootPageId: 1
routeEnhancers:
  NewsPlugin:
    type: Extbase
    extension: News
    plugin: Pi1
    routes:
      -
        routePath: '/{news_title}'
        _controller: 'News::detail'
        _arguments:
          news_title: news
    defaultController: 'News::list'
    aspects:
      news_title:
        type: PersistedAliasMapper
        tableName: tx_news_domain_model_news
        routeFieldName: path_segment
websiteTitle: Lueg
